server:
  port: 8080
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/shardingjdbc?useUnicode=true&charaterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      connection-test-query: SELECT 1 FROM DUAL
#      pool-name: pool
#      maximum-pool-size: 15
#      minimum-idle: 5
#      max-lifetime: 1765000
#      idle-timeout: 600000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
#      generate-ddl: true
#      show-sql: true
    hibernate:
      ddl-auto: none
      #在进行领域映射时,首字母小写，大写字母变为下划线加小写
      naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      naming.implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  profiles:
    include: sharding
